# Generated by Django 5.0.6 on 2024-06-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0001_initial'),
        ('post_app', '0002_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
