# Generated by Django 5.0.6 on 2024-06-16 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_alter_post_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
    ]
