# Generated by Django 5.0.6 on 2024-06-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0008_remove_post_content_post_brand_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='car_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
